### ISSUE TITLE
BotMod -- bot say -- Wont work with sentances

### ISSUE THREAD

**Issue by NickMarley** [Michelele/Violet#11]
[http://i.imgur.com/GKoVjfV.png](url)

**Comment by v0idst4r** [comment]
You mean spaces?

**Comment by NickMarley** [comment]
Correct @v0idst4r

**Comment by v0idst4r** [comment]
I think replacing

p.sendChatMessage(c[1]);

with

p.sendChatMessage(s.substr(4));

would work

**Comment by v0idst4r** [comment]
substring* been doing too much php.

**Comment by Michelele** [comment]
Oh i see, ill just use s.split(" ", 2)
