### ISSUE TITLE
stop committing every file every time you push

### ISSUE THREAD

**Issue by nerd** [Michelele/Violet#12]
it makes it really difficult to see what you've done.

**Comment by Michelele** [comment]
Hmm ok ill see

**Comment by Michelele** [comment]
Ok further changes will be done using git commit -a

**Comment by nerd** [comment]
that's not really how you do it but i mean whatever

**Comment by Michelele** [comment]
didnt work this time, ill fix it for next time, also how do u mean?

**Comment by nerd** [comment]
don't run git add when you commit
