### ISSUE TITLE
stop making everything static

### ISSUE THREAD

**Issue by nerd** [Michelele/Violet#9]
there are better ways of doing it. some things warrant the static keyword, but not everything.

**Comment by v0idst4r** [comment]
Y tho

**Comment by nerd** [comment]
when everything is static, it's harder to control initialization, access, etc.
also there's no reason for any of this to be static. a singleton is better in this case.

**Comment by Michelele** [comment]
This will be fixed, makes it easier to read also

**Comment by Michelele** [comment]
Also fills in the pattern of class hierarchy kek
